# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-09 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, upload_to=b'photo/'),
        ),
    ]
