# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-10 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20170509_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.CharField(default=1, help_text=b'Please enter an email of the business', max_length=400),
        ),
        migrations.AddField(
            model_name='book',
            name='phone_number',
            field=models.CharField(default=1, help_text=b'Please enter the phone number of the business', max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text=b'Please enter the type of the business', to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text=b'Please enter your business working hours', max_length=13, verbose_name=b'ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text=b'Please enter the location of the business', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text=b'Enter a brief description of the Business', max_length=1000),
        ),
    ]
