# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-16 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20170510_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
        migrations.AlterField(
            model_name='book',
            name='about_us',
            field=models.TextField(help_text='Enter the story about you', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.CharField(default=1, help_text='Please enter an email of the business', max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Please enter the type of the business', to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='Please enter your business working hours', max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Please enter the location of the business', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mission',
            field=models.TextField(help_text='Enter your mission', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone_number',
            field=models.CharField(default=1, help_text='Please enter the phone number of the business', max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the Business', max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='values',
            field=models.TextField(help_text='Enter your mission', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='vision',
            field=models.TextField(help_text='Enter your vision', max_length=300, null=True),
        ),
    ]
